#!/bin/bash

source ./testlib
SLEEP_SEC=20


if [ $# -eq 0 ] || ( [ $1 != 'up' ] && [ $1 != 'down' ] ) ; then
    echo "Usage: ./scale [up/down]"
    exit 1
fi

op=$1

function sleep_sec {
    dbg_print "Sleeping $1 seconds..."
    sleep $1
}

kill_topo
sleep_sec ${SLEEP_SEC}

kill_supervisors
sleep_sec ${SLEEP_SEC}

m=`cat ./supervisors`
if [ $op == 'up' ] ; then
    # scale up
    m=$((m + 1))
else
    # scale down
    m=`max "$((m - 1)) 0"`
fi

run_supervisors $m
sleep_sec ${SLEEP_SEC}

run_topo $m
notify_server $m
