#!/bin/bash

source ./testlib
KILL_SUPERVISORS_SLEEP_SEC=3
RUN_SUPERVISORS_SLEEP_SEC=20


if [ $# -eq 0 ] || ( [ $1 != 'up' ] && [ $1 != 'down' ] ) ; then
    echo "Usage: ./scale [up/down]"
    exit 1
fi

op=$1

kill_topo

m=`cat ./supervisors`

kill_supervisors
sleep_sec ${KILL_SUPERVISORS_SLEEP_SEC}

m=`echo $m | sed 's/^0*//'`
if [ $op == 'up' ] ; then
    # scale up
    new_m=$((m + 1))
    dbg_print "Scaling up: $m -> ${new_m}"
else
    # scale down
    new_m=`max "$((m - 1)) 0"`
    dbg_print "Scaling down: $m -> ${new_m}"
fi
m=${new_m}

notify_server $m
run_supervisors $m
sleep_sec ${RUN_SUPERVISORS_SLEEP_SEC}

run_topo $m
