#!/bin/bash

cd ./monitors/bytes/; ./bytesin & cd ../../
pid_bytesin=`pgrep bytesin`
if [[ ! -z ${pid_bytesin} ]] ; then
    echo "Started bytesin monitor (PID:${pid_bytesin::-1})"
fi

cd ./monitors/bytes/; ./bytesout & cd ../../
pid_bytesout=`pgrep bytesout`
if [[ ! -z ${pid_bytesout} ]] ; then
    echo "Started bytesout monitor (PID:${pid_bytesout::-1})"
fi

cd ./monitors/offsets/; ./offsets & cd ../../
pid_offsets=`pgrep offsets`
if [[ ! -z ${pid_offsets} ]] ; then
    echo "Started offsets monitor (PID:${pid_offsets::-1})"
fi

cd ./monitors/msgsize/; ./msgsize & cd ../../
pid_msgsize=`pgrep msgsize`
if [[ ! -z ${pid_msgsize} ]] ; then
    echo "Started msgsize monitor (PID:${pid_msgsize::-1})"
fi






