#!/bin/bash

cd ./monitors/bytes/; ./bytesin & cd ../../
pid_bytesin=`pgrep bytesin`
if [[ ! -z ${pid_bytesin} ]] ; then
    echo "Started bytesin monitor (PID:${pid_bytesin::-1})"
fi

cd ./monitors/bytes/; ./bytesout & cd ../../
pid_bytesout=`pgrep bytesout`
if [[ ! -z ${pid_bytesout} ]] ; then
    echo "Started bytesout monitor (PID:${pid_bytesout::-1})"
fi

cd ./monitors/offsets/; ./offsets & cd ../../
pid_offsets=`pgrep offsets`
if [[ ! -z ${pid_offsets} ]] ; then
    echo "Started offsets monitor (PID:${pid_offsets::-1})"
fi

cd ./monitors/jmx/; ./jmx & cd ../../
pid_jmx=`pgrep jmx`
if [[ ! -z ${pid_jmx} ]] ; then
    echo "Started jmx monitor (PID:${pid_jmx::-1})"
fi
