#!/bin/bash

cd ./monitors/bytes/; ./bytesin & cd ../../
pid_bytesin=`pgrep bytesin`
if [[ ! -z ${pid_bytesin} ]] ; then
    echo "Started bytesin monitor (PID:${pid_bytesin::-1})"
fi

cd ./monitors/bytes/; ./bytesout & cd ../../
pid_bytesout=`pgrep bytesout`
if [[ ! -z ${pid_bytesout} ]] ; then
    echo "Started bytesout monitor (PID:${pid_bytesout::-1})"
fi

cd ./monitors/offsets/; ./offsets & cd ../../
pid_offsets=`pgrep offsets`
if [[ ! -z ${pid_offsets} ]] ; then
    echo "Started offsets monitor (PID:${pid_offsets::-1})"
fi

cd ./monitors/minavg/; ./minavg & cd ../../
pid_minavg=`pgrep minavg`
if [[ ! -z ${pid_minavg} ]] ; then
    echo "Started minavg monitor (PID:${pid_minavg::-1})"
fi






