#!/bin/bash

source ../../config

script -c "python lag-monitor.py --topic ${TOPIC} --group_id ${GROUP_ID} --interval_sec ${LAG_MONITOR_INTERVAL_SEC}" | stdbuf -oL grep "offsets" | stdbuf -oL sed 's/^{/set {"args": {/' | stdbuf -oL sed 's/]}/]}}/' | nc ${METRICS_SERVER_HOST} ${METRICS_SERVER_PORT}
